### PR TITLE
Log stdout when commands fail

### LINKED ISSUE #40: fix/improve logging
I found a couple issues in Lerna which I think you have inherited that are pretty bad to have lying around. Just bringing these to your attention:
- https://github.com/lerna/lerna/pull/372
- https://github.com/lerna/lerna/pull/373

### PR DESCRIPTION
**Pull request by gigabo**
ChildProcessUtilities now returns stdout as the second argument of
a callback. logifyAsync will check for the presence of a second
argument and log it out in the case of an error, too.

This fixes #40.

Need to merge this non-squash to preserve @seansfkelley's authorship.

### CODE REVIEW

File: src/logger.js [hunk 1]
```diff
@@ -80,6 +80,9 @@ class Logger {
       args.push((error, value) => {
         if (error) {
           logger.error(msg);
+          if (value) {
+            logger.error(value);
```
Comment (rygine) [inline src/logger.js:84]: why an error log?

**Review by rygine — APPROVED** [review]
LGTM

File: src/logger.js (hunk 1 above)
Comment (gigabo) [reply src/logger.js:84]: This is in the `if (error)` case.

It's augmenting the error output with whatever happened to be in `value` when the error arose.

**Comment by gigabo** [comment]
Thanks @seansfkelley!
